<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGlnsgfv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGlnsgfv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGlnsgfv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGlnsgfv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGlnsgfv\appProdProjectContainer([
    'container.build_hash' => 'Glnsgfv',
    'container.build_id' => '4c724b06',
    'container.build_time' => 1690055717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGlnsgfv');
